openapi: 3.0.0
info:
  title: Sample API
  description: |
    ```html
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Login Page</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f8f9fa;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
            }

            .container {
                text-align: center;
                background: white;
                border-radius: 8px;
                padding: 2rem;
                box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
            }

            h1 {
                color: #e63946;
                font-size: 2.5rem;
                margin-bottom: 1rem;
            }

            input {
                width: 100%;
                padding: 10px;
                margin: 10px 0;
                border: 1px solid #ccc;
                border-radius: 4px;
            }

            .btn {
                width: 100%;
                padding: 10px;
                border: none;
                border-radius: 4px;
                cursor: pointer;
                color: white;
                font-size: 1rem;
                margin: 10px 0;
            }

            .login {
                background-color: #e63946;
            }

            .social-btn {
                display: inline-block;
                width: 32%;
                margin: 0 1%;
                padding: 10px;
                border-radius: 4px;
                font-size: 1rem;
                color: white;
                text-align: center;
                cursor: pointer;
            }

            .google {
                background-color: #db4437;
            }

            .facebook {
                background-color: #3b5998;
            }

            .apple {
                background-color: #000000;
            }

            .forgot-password {
                margin: 10px 0;
                font-size: 0.9rem;
                color: #6c757d;
            }

            .signup {
                margin-top: 15px;
                font-size: 0.9rem;
                color: #e63946;
            }
        </style>
    </head>
    <body>

    <div class="container">
        <h1>Deriv</h1>
        <p>Welcome back</p>

        <marquee>
            <h1>Stored XSS JS and HTML Injection</h1>
            <h1>by zhirosec</h1>
        </marquee>

        <p>Or continue with</p>
        
        <div>
            <a href="https://google.com"><button class="social-btn google">Google</button></a>
            <a href="https://www.facebook.com/"><button class="social-btn facebook">Facebook</button></a>
            <a href="https://www.apple.com/"><button class="social-btn apple">Apple</button></a>
        </div>

        <p class="signup">Don’t have an account yet? <a href="https://google.com">Sign up</a></p>
    </div>

    </body>
    </html>
    ```
  version: 1.0.0
paths: {}
components: {}
